### ISSUE TITLE
Need to reset expected value

### ISSUE THREAD

**Issue by aleden** [tchajed/futex-tutorial#1]
Beware: when `atomic_compare_exchange_weak()` fails it will set expected equal to the current value, i.e. `LOCKED`. The next time around when it is called `expected` will equal `LOCKED` when it *should be* `UNLOCKED`. One need to reset `expected` (i.e. `expected = UNLOCKED;`) on line 19. https://github.com/tchajed/futex-tutorial/blob/5001c874c253dcc9a4945eacb4285b43ea85dddd/mutex.c#L19

I know this is a trivial github project but it's like the first thing that shows up on google for implementing a mutex on linux.

**Comment by tchajed** [comment]
Thanks, I really appreciate that you pointed this out! While this repo is indeed not a useful piece of software I wouldn't feel right having a tutorial steer people wrong.

The example program called futex_demo in the [futex(2) man page](https://man7.org/linux/man-pages/man2/futex.2.html) seems to have an incorrect explanation of `atomic_compare_exchange_strong` which may be where I got the wrong semantics from. It would be great to submit a patch to that.
